refactor: use tailwind native aspect-ratio utility class
leerob/image-gallery-supabase-tailwind-nextjs pull request #2
Opened 2022-03-31 09:57 UTC by emmanuelchucks

I'm curious if there is any reason you chose to use the plugin instead of the utility class that comes with Tailwind.

Am I missing something?

2022-03-31 14:12 UTC, leerob approved these changes
Good call!

2022-03-31 14:13 UTC, leerob requested changes
Huh, interesting - actually seems like it's not working on the preview deploy.

2022-04-01 22:28 UTC, emmanuelchucks commented
My bad. Should have used "position: relative" on Image's parent element

2022-04-02 15:59 UTC, leerob commented on pages/index.tsx
> +      <div className="relative aspect-square w-full overflow-hidden rounded-lg bg-gray-200 xl:aspect-[7/8]">
```suggestion
      <div className="aspect-square w-full overflow-hidden rounded-lg bg-gray-200 xl:aspect-[7/8]">
```

2022-04-02 15:59 UTC, leerob commented on pages/index.tsx
>      <a href={image.href} className="group">
```suggestion
    <a href={image.href} className="group relative">
```

2022-04-04 19:13 UTC, emmanuelchucks commented
"Position: relative" should be on direct parent of image to prevent covering up the name and twitter handle. Check my latest commit.

2022-11-05 01:38 UTC, closed without merging